### ISSUE TITLE
Bug in Roi Classifier

### ISSUE THREAD

**Issue by maten21** [VervaekeLab/NANSEN#10]
In the Roi Classifier when the sorting is set anything other than "none" it does not show the roi outlines, and the toggle button does not work. 
![image](https://github.com/VervaekeLab/NANSEN/assets/151050400/ca31cf87-f899-4254-9349-f25ecb76b77b)

**Comment by ehennestad** [comment]
Did you see this error message in the command line:
`Error using cell/strcat
All nonscalar inputs must be the same size.

Error in mclassifier.manualClassifier/getItemText (line 1189)
            cellOfStr = strcat(cellOfStr, valuesStr);
`

**Comment by maten21** [comment]
Yes, the same error message even after the update:

```
Error using cell/strcat
All nonscalar inputs must be the same size.

Error in mclassifier.manualClassifier/getItemText (line 1189)
            cellOfStr = strcat(cellOfStr, valuesStr);

Error in roiclassifier.App/updateTile (line 852)
            roiLabels = obj.getItemText(roiInd);

Error in mclassifier.manualClassifier/updateView (line 1016)
        obj.updateTile(obj.displayedItems, 1:numTilesToUpdate)

Error in roiclassifier.App/updateView (line 635)
            updateView@mclassifier.manualClassifier(obj, src, event, mode)

Error in mclassifier.manualClassifier>@(varargin)obj.updateView(varargin{:}) (line 376)
        inputbox(end).Callback = {@obj.updateView, 'change sort order'};
 
```
