### ISSUE TITLE
Suggestion for improving ROI Manager

### ISSUE THREAD

**Issue by maten21** [VervaekeLab/NANSEN#11]
1.) Keyboard-shortcuts zooming: **Fixed**

I am missing a lot the Z/shift+Z zoom function from the old ROI Manager, can you add that? 
Now the Q and W only activates the mouse tool which I find very unpractical as requires many steps: 1 selecting zoom function, 2 click,  3 selecting ROI drawing tool, 4 selecting zoom out function, 5 click, (6. select default or other mouse tool) compared to keeping the mouse in ROI drawing mode at the target ROI and zooming with the keys. 

2.) Keyboard-shortcuts deleting ROI:  **Fixed**

I have found that deleting ROIs with "backspace" is quite unintuitive for new people. Could you also add the "Delete" key by also keeping "Backspace"? 

3.) The 'e' edit ROI function was also useful in some cases although I agree it was also annoying at times. I am not necessarily suggesting to reintroduce it as it was originally but some ways to do minor adjustments would be useful. One longtime idea is to be able to edit ROIs directly at the magnified ROI Info image. **New issue created #18** 

4.) In my opinion the ROI Info image GOI component would be better placed by taking up space from the ROI list instead of the Signal viewer at least it could jump there when the signal viewer turned off. 

4.5.) I find the proportions of the Signal viewer are excessive therefore I tend to turn it off to be able to see the FOV as large as possible.  If not too difficult to implement, some option to rescale GUI elements would be quite useful, especially the optimal GUI layout can vary depending on the monitor.  A probably quite simple but not the most elegant way would be to add a GUI layout tab to the params where the proportions could be changed. The elegant way would be when one can grab and move the GUI element separators like in Matlab. **Partly fixed**

5.) I would really really like to use a mouse scroll factor >100. Instead of the slider between 1-10 it could be just a numerical input without upper limit or an extra multiplication factor that multiplies the slider value.  **Fixed**

6.) It is not clear what the "Signal rastermap" and the "Roi history plot" toggles do other than turning off the signal viewer window. **Fixed**

7.) In the ROI list window there is no horizontal scroll bar so many of the columns are inaccessible.  **Fixed**

I will probably have more ideas and will update this post or the thread. :)

**Comment by ehennestad** [comment]
1) +/- buttons should do what you want with zoom, although I don't remember if I tested this on Windows. Z/shift+z is reserved for undo/redo operations, but I could potentially add other keys.

2) Good idea. Will add this.

3) Editing a roi on the roi thumbnail image should be possible. It might even be possible to use the autodetect tool on that image now, by clicking the image and then pressing the 'a' key. 

4) Good idea, layout wise, this should not be too difficult to do.
4.5) I added an extra item on the dropdown menu to change app layout. You can either set a fixed size by entering the number in pixels, or a variable size by entering a number followed by x. So for example 2x, 1x would make the first row 2 times larger than the second row.

5) Done

6) They are not implemented yet, best to remove them for the time being.

7) Changed so the horizontal scroller is visible on Windows (its possible to scroll horizontally with a trackpad, but I assume many PCs are stationary with a desktop mouse)

**Comment by maten21** [comment]
_1.) Zoom:_ +/- buttons do not seem to work on my laptop. Those are not too practical anyway because it is difficult to find on the main keybord (laptop) or on a numerical one those are on the right end and the right hand is already occupied with the mouse while the left hand is around D and A. 
Thinking about it, the most convenient would be if holding down a button would temporarily change the function of the mouse scroll to zoom. I t could be the Z, or actually Ctrl + scroll is the zoom pretty much everywhere on Windows.

_3.) Editing a roi on the roi thumbnail:_ Autodetection tool can be activated but does not do anything when I click. How should the editing work?  

_4.) App layout:_ This works nicely! An idea, on long term it could be done by sliders also acting as separators something similar, although this seams to be sensitive for updating by clicking on any part of the scale: 
![image](https://github.com/VervaekeLab/NANSEN/assets/151050400/5672f523-1e2d-4ff7-94e1-be045245933c)

5.) This still does not work for some reason, maybe the settings are saved and loaded from user data? 

![image](https://github.com/VervaekeLab/NANSEN/assets/151050400/fea3e467-33df-44e5-b634-02e80e2fc360)

**Comment by maten21** [comment]
8) When I draw a new ROI the "active window" becomes the ROI list so for instance the arrows are navigating in the spreadsheet instead of the imviewer window. Probably because of the same reason I can not switch between selection tools (e.g. O -> A) unless I click first to a neutral part of the GUI eg the edge. 
There are probably other examples when the mouse tool does not do what it should first unless selecting another tool or clicking somewhere, maybe the same underlying issue?
