### ISSUE TITLE
not able to open h5 files

### ISSUE THREAD

**Issue by ashishalrashid** [VervaekeLab/NANSEN#12]
![Screenshot 2023-11-29 152757](https://github.com/VervaekeLab/NANSEN/assets/135253420/df34870f-a970-4f9d-a8b4-a558255f795b)

**Comment by ehennestad** [comment]
Hi!
This is correct. Out of the box Nansen do support some two photon data formats, but does not provide direct support for h5 files as these are very heterogeneous. 

To provide a brief overview on the idea of how to open this file, you can read the section on Variables in the Wiki:
https://github.com/VervaekeLab/NANSEN/wiki/Basic-Concepts#variables

I am currently working on a system to make it more user-friendly to create custom file adapters, but if you need something fast I could advise you but I need a couple of details about the file.

Is this file containing two photon data? Under what internal path of the file is the data located. Is there additional metadata in the file about the dimensions and type of the data?

**Comment by ashishalrashid** [comment]
The file comprises two sets of photon data, specifically sourced from the Testing/Example data within the CIAtah package developed by Biafra Ahanonu. 

While the file is available for sharing or download (500MB), it is not necessary or urgent.

I am currently comparing and evaluating various 2-photon imaging analysis software solutions. In the interest of maintaining consistency, I had attempted to test with the HDF5 file from the CIAtah package. 

I would appreciate it if you could provide any test data that can be practically shared to assess the software's capabilities.

**Comment by ehennestad** [comment]
I have added a file adapter to read the file.

You would have to open nansen using `nansen`, go to the following menu: Nansen -> Configure -> Variables and then do something like this: 

<img width="880" alt="Screenshot 2023-12-07 at 18 35 30" src="https://github.com/VervaekeLab/NANSEN/assets/17237719/76709e98-5549-4d9a-b638-37622d5d4b04">

Select the data location where the file is located, add `concat_recording*` in the filename expression field and select the CiatahDemoFile adapter.

You should then be able to open the file from the file viewer or run motion correction from the methods under the Processing menu.

**Comment by ehennestad** [comment]
Please also see this [wiki section](https://github.com/VervaekeLab/NANSEN/wiki/Keyboard-Shortcuts#menu-options-session-methods) for some tips on working with the menus containing session methods

**Comment by ehennestad** [comment]
I will close this issue for now. Please feel free to re-open if you have more questions!
