### ISSUE TITLE
Bugs in main NANSEN app

### ISSUE THREAD

**Issue by maten21** [VervaekeLab/NANSEN#14]
When I try to create a new pipeline or edit existing one: 

> Output argument "S" (and possibly others) not assigned a value in the execution with "ophys.twophoton.process.signalExtraction/extractSignalsMultiChannel/getDefaultOptions" function.
> 
> Error in nansen.manage.OptionsManager/findPresetsFromOptionsMixinClass (line 958)
>             opts = fcnHandle();
> 
> Error in nansen.manage.OptionsManager/findPresetOptions (line 898)
>                     optionsEntry = obj.findPresetsFromOptionsMixinClass();
> 
> Error in nansen.manage.OptionsManager (line 224)
>             obj.findPresetOptions()
> 
> Error in nansen.OptionsManager (line 9)
>     obj = nansen.manage.OptionsManager(varargin{:});
> 
> Error in nansen.config.SessionMethodsCatalog.getOptionsAlternatives (line 184)
>             optManager = nansen.OptionsManager(item.FunctionName);
> 
> Error in nansen.config.SessionMethodsCatalog/addOptionsAlternative (line 86)
>                     obj.getOptionsAlternatives(obj.Data(i));
> 
> Error in nansen.pipeline.uiCreatePipeline (line 23)
>     smCatalog.addOptionsAlternative()
> 
> Error in nansen.App/onCreateNewPipelineMenuItemClicked (line 3602)
>             hUi = nansen.pipeline.uiCreatePipeline();
> 
> Error in nansen.App>@(varargin)app.onCreateNewPipelineMenuItemClicked(varargin{:}) (line 662)
>             mitem.MenuSelectedFcn = @app.onCreateNewPipelineMenuItemClicked;
>  
> Error while evaluating Menu Callback.
> 

Configure pipeline assignment keeps loading forever:
![image](https://github.com/VervaekeLab/NANSEN/assets/151050400/2171e4ce-c7ef-4b27-85b8-0e4fc5027679)

**Comment by ehennestad** [comment]
@maten21 All these should be fixed now.

For the BOT preferences, I removed the Menu item as it is not relevant to keep it in nansen at the moment
